<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<meta name="apple-mobile-web-app-capable" content="yes">
		<!--<meta http-equiv="refresh" content="300">-->
		<title>Chip Data</title> 
		<link rel="stylesheet" type="text/css" href="global.css">
	</head>

	<body>
		<div style="margin: 0 auto; width:100%; position: fixed; top: 0px; left: 0px; text-align: center;height: 60px; background-color: rgb(10,100,170); color: #FFFFFF; z-index:1;">
			<table width="100%" border="0" align="center" rules=none cellspacing=0 cellpadding=0>
				<tr>
					<td colspan="1" align="right" valign="center" width="8%">
					</td>
					<td colspan="1" align="left" valign="center" width="54%" height="60px" style="overflow: hidden;">
						<h1>ATLAS Lab Environment Monitor System</h1>
					</td>
					<td colspan="1" align="right" valign="center" height="60px" style="line-height:20px;overflow: hidden;">
						<h3>
							General Status: NORMAL<br>
							LBL pixelKr project team at Bekeley
						</h3>
					</td>
					<td colspan="1" align="right" valign="center" width="8%">
					</td>
				</tr>
			</table>
		</div>

		<div id="Float_TAG" onclick="(function(){/*getElementById('Flaot_TG').style.display='none';*/location.reload(true);})()" style="z-index: 4">  
    		<p>Last Update #*CURRENT_TIMESTAMP*#</p>
		</div>

		<div style="width: 85%; max-width: 1280px; position: relative; height: 60px; display: block; align-self: center;">
		</div><!--This div is meant to take the position of the head banner-->

		<center>
			<table border="0" align="center" style="border-style: none; table-layout:fixed; width: 85%; max-width: 1280px;" rules=none cellspacing=0>
				<col style="width: 4% " />
				<col style="width: 0.4% " />
				<col style="width: 4% " />
				<col style="width: 6% " />
				<col />
				<col style="width: 25% " />
				<col style="width: 30% " />
				<tbody>

					<tr style="height:60px">
						<td style="background-color: rgba(255,255,255,0);color: #000;text-align: left;" colspan="6">
							<h2>Chip Data</h2>
						</td>
					</tr>

					<tr style="height:40px">
						<td colspan="2" class="table_header unactive" id="Table_Title_0" onclick="switch_col_display(0)">
							<p>WF</p>
						</td>
						<td colspan="1" class="table_header unactive" id="Table_Title_1" onclick="switch_col_display(1)">
							<p>BD</p>
						</td>
						<td colspan="1" class="table_header unactive" id="Table_Title_2" onclick="switch_col_display(2)">
							<p>C/R</p>
						</td>
						<td colspan="1" class="table_header unactive" id="Table_Title_3" onclick="switch_col_display(3)">
							<p>STATUS</p>
						</td>
						<td colspan="1" class="table_header unactive" id="Table_Title_4" onclick="switch_col_display(3)">
							<p>FLIP_TO</p>
						</td>
						<td colspan="1" class="table_header unactive" id="Table_Title_5" onclick="switch_col_display(4)">
							<p>LOCATION</p>
						</td>
					</tr>

					<tr style="height: 8px">
						<td colspan="6" style="background-color:rgba(255,255,255,0);;text-align:center;">
					</tr>

					<tr class="log_table" id="data-row-#*row_count*#">#*!LineMerge$1*##*!intv$1*#
							<td style="line-height:28px;background-color:#AAAAAA;text-align: center; color: #fff;">
								<p><!--DATA-->#*Wafer$00000000*#</p>
							</td>
							<td style="line-height:28px;background-color:#4BC2C5;text-align: center; color: #fff;">
							</td>
							<td style="line-height:28px;background-color:#DDDDDD;text-align: center; color: #000;">
								<p><!--DATA-->#*Board$00000000*#</p>
							</td>
							<td style="line-height:28px;background-color:#EEEEEE;text-align: center; color: #000;">
								<p><!--DATA-->#*row$00000000*#-#*col$00000000*#</p>
							</td>
							<td style="line-height:28px;background-color:#DDEEE8;text-align: center; color: #000;">
								<p><!--DATA-->#*Status$00000000*#</p>
							</td>
							<td style="line-height:28px;background-color:#EEEEEE;text-align: center; color: #000;">
								<p><!--DATA-->#*Flip_to$00000000*#</p>
							</td>
							<td style="line-height:28px;background-color:#DDDDDD;text-align: center; color: #000000;">
								<p><!--DATA-->#*Location$00000000*#</p>
							</td>
					</tr>
					<tr style="height: 8px" id="data-row-blk-#*row_count*#">
						<td colspan="7" style="background-color:rgba(255,255,255,0);text-align:center;">
					</tr>
					#*!LineMerge$0*#
					<tr style="height: 3px">
						<td colspan="7" style="background-color:#4BC2C5;text-align:center;">
					</tr>		 
					<tr style="height: 10px">
						<td colspan="7" style="background-color:#FFFFFF;text-align:center;">
					</tr>	
				</tbody>
			</table>
		</center>
	</body>
</html>