<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<meta name="apple-mobile-web-app-capable" content="yes">
		<!--<meta http-equiv="refresh" content="300">-->
		<title>Env Monitor</title> 
		<link rel="stylesheet" type="text/css" href="index.css">
	</head>

	<body>
		<div style="margin: 0 auto; width:100%; position: fixed; top: 0px; left: 0px; text-align: center;height: 60px; background-color: rgb(10,100,170); color: #FFFFFF; z-index:1;">
			<table width="100%" border="0" align="center" rules=none cellspacing=0 cellpadding=0>
				<tr>
					<td colspan="1" align="right" valign="center" width="8%">
					</td>
					<td colspan="1" align="left" valign="center" width="54%" height="60px" style="overflow: hidden;">
						<h1>ATLAS Lab Environment Monitor System</h1>
					</td>
					<td colspan="1" align="right" valign="center" height="60px" style="line-height:20px;overflow: hidden;">
						<h3>
							General Status: #*General_Status*#<br>
							LBL pixelKr project team at Bekeley
						</h3>
					</td>
					<td colspan="1" align="right" valign="center" width="8%">
					</td>
				</tr>
			</table>
		</div>

		<div id="Float_TAG" onclick="(function(){/*getElementById('Flaot_TG').style.display='none';*/location.reload(true);})()" style="z-index: 4">  
    		<p>Last Update #*CURRENT_TIMESTAMP*#</p>
		</div>  

		<div style="position: relative; height: 80px; display: block;" align="center">
		</div>

		<center>
			<canvas id="Envrionment Status" style="width:85%;" oncontextmenu="DBG_Switch();">
			</canvas>
		</center>


		<div style="position: relative; height: 5px; display: block;" align="center">
		</div>

		<table width="85%" border="0" align="center" style="border-style: none; table-layout:fixed" rules=none cellspacing=0>
			<col style="width: 4% " />
			<col style="width: 0.4% " />
			<col style="width: 12% " />
			<col style="width: 12% " />
			<col />
			<col style="width: 18% " />
			<tbody>

				<tr style="height:60px">
					<td style="background-color: rgba(255,255,255,0);color: #000;text-align: left;" colspan="6">
						<h2>System Log</h2>
					</td>
				</tr>	

				<tr style="height:40px">
					<td style="background-color: #4BC2C5;color: #FFF;text-align: center;">
						<p>ID</p>
					</td>
					<td style="background-color: #4BC2C5;color: #FFF;text-align: center;">
					</td>
					<td style="background-color: #4BC2C5;color: #FFF;text-align: center;">
						<p>SOURCE</p>
					</td>
					<td style="background-color: #4BC2C5;color: #FFF;text-align: center;">
						<p>TYPE</p>
					</td>
					<td style="background-color: #4BC2C5;color: #FFF;text-align: center;">
						<p>CONTENT</p>
					</td>
					<td style="background-color: #4BC2C5;color: #FFF;text-align: center;">
						<p>DATE</p>
					</td>
				</tr>

				<tr style="height: 8px">
					<td colspan="6" style="background-color:rgba(255,255,255,0);;text-align:center;">
				</tr>
				<tr>#*!LineMerge$1*#
						<td style="line-height:28px;background-color:#AAAAAA;text-align: center; color: #fff;">
							<p>#*!intv$1*##*<table$Log>ID$00000000*#</p>
						</td>
						<td style="line-height:28px;background-color:#4BC2C5;text-align: center; color: #fff;">
						</td>
						<td style="line-height:28px;background-color:#DDDDDD;text-align: center; color: #000;">
							<p>#*!intv$1*##*<table$Log>MSG_Source$00000000*#</p>
						</td>
						<td style="line-height:28px;background-color:#EEEEEE;text-align: center; color: #000;">
							<p>#*!intv$1*##*<table$Log>MSG_Type$00000000*#</p>
						</td>
						<td style="line-height:28px;background-color:#DDEEE8;text-align: center; color: #000;">
							<p>#*!intv$1*##*<table$Log>MSG_Index$00000000*#</p>
						</td>
						<td style="line-height:28px;background-color:#DDDDDD;text-align: center; color: #000000;">
							<p>#*!intv$1*##*<table$Log>Date_Time$00000000*#</p>
						</td>
				</tr>
				<tr style="height: 8px">
					<td colspan="6" style="background-color:rgba(255,255,255,0);text-align:center;">
				</tr>#*!LineMerge$0*#
				<tr style="height: 3px">
					<td colspan="6" style="background-color:#4BC2C5;text-align:center;">
				</tr>		 
				<tr style="height: 10px">
					<td colspan="6" style="background-color:#FFFFFF;text-align:center;">
				</tr>	
				<tr style="height: 30px">
					<td colspan="6" style="background-color:#FFFFFF;text-align:center;">
						<a href="Version-Gallery.html" style="color: #666666;">
							<p>Click HERE For Verison Gallery</p>
						</a>
				</tr>
			</tbody>
		</table>


		<div style="margin: 0 auto; width:85%; position: relative; border:none; text-align: center;height: 80px; background-color: #FFFFFF; color: #666; z-index:1; padding: 0px; vertical-align: middle;">
				<div style="margin: 0 auto; width: 100% ; height: 100% ; position: absolute; left: 0px; top: 0px; z-index: 2; text-align: center; vertical-align: middle;">
					<p><br>By Yuxuan Zhang</p>
					<p>APRIL 2018</p>
				</div>
				<div style="margin: 0 auto; width: 100% ; height: 100% ; position: absolute; left: 0px; top: 0px; z-index: 3">
					<a href="https://yuxuanzhang.myportfolio.com" style="display:block; width:100%; height:100%;"></a>
				</div>
		</div>

		<!--######################################################################################-->
		<script type="text/javascript" src="ZChart.js?V2.01"></script>
		<script type="text/javascript">	
			var Chart_1=ZChart.create("Envrionment Status",Enviornment_Status_Style);
		</script>
	</body>
</html>